version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  # choco install sbt
  - ps: |
      $MVNDIR = 'C:\bin\apache-maven-3.2.5\'
      if (!(Test-Path -Path $MVNDIR )) {
        Write-Host (Test-Path -Path $MVNDIR)
        Write-Host 'Installing Maven'
        choco install maven -Version 3.2.5
      } else {
        Write-Host 'Found Maven cached installation'
      }
  - cmd: SET PATH=C:\bin\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -DskipTest
  # TODO(ochafik): Build native libs here (need to convert .vcproj to MSBuild script)
test_script:
  - mvn test -B
  - SET BRIDJ_PROTECTED=1
  - mvn test -o -Dtest=ExceptionsTest
cache:
  - C:\bin\apache-maven-3.2.5\
  - C:\Users\appveyor\.m2
